version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: faker
    versions:
    - 2.15.1
    - 2.16.0
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: sentry-raven
    versions:
    - 3.1.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: eslint-plugin-html
    versions:
    - 6.1.1
